### PR TITLE
Remove unnecessary config class

### PR DESCRIPTION
**Pull request by martinezcoder**
Since we implemented the `OpenMeteo.configuration` class, the `Client::Config` class is not necessary anymore.

### CODE REVIEW

**Comment by martinezcoder** [comment]
I need to rebase the last main with new commits merged.

**Comment by peterfication** [comment]
But the `OpenMeteo.configuration` is meant as a global config, while the `Client::Config` is meant for individual clients. Or do I miss something?

**Comment by martinezcoder** [comment]
You can still send a custom config to each class only by replacing the default `config` class in the initializer. Imho, `OpenMeteo::Client::Config` and `OpenMeteo::Configuration` are the same, and have the same configurable attributes.

If in any context, the consumer of the library wants to change the configuration object, they only have to call the client with other config class, e.g.:

```ruby
client = OpenMeteo::Client.new(config: MyConfigClass.new)
forecast = OpenMeteo::Forecast.new(client: client)
```

Maybe the problem in our code is that we still have to fix some classes to initialize the same config file in the dependent classes. For example, the Forecast class is initializing the response wrapper but it is not using the same config initialization as the client, so we have to do weird things like:

```ruby
client = OpenMeteo::Client.new(config: MyConfigClass.new)
response_wrapper = OpenMeteo::ResponseWrapper.new(config: MyConfigClass.new)
forecast = OpenMeteo::Forecast.new(client: client, response_wrapper: response_wrapper)
```

When it would be easier if we could do something like:

```ruby
forecast = OpenMeteo::Forecast.new(config: MyConfigClass.new)
```

and we ensure that `client` and `response_wrapper` classes initialize the same config.

**Comment by peterfication** [comment]
But if I want to change one config option, then I would need to implement everything for `MyConfigClass`, right?

**Comment by martinezcoder** [comment]
As agreed, I am closing this PR because we would need to create a new class to modify the configuration and that's annoying.

**Pull request closed without merging**
